info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    
zuul:
  routes:
    stores: /stores/**
    customers: /customers/**
    foo: /foo/**

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0